name: league
channels:
  - conda-forge
  - defaults
  - pip:
    - absl-py
    - alabaster
    - albumentations
    - apex
    - appdirs
    - astor
    - attrs
    - babel
    - backcall
    - bcrypt
    - black
    - bleach
    - boto
    - botocore
    - cached-property
    - cachetools
    - catboost
    - chardet
    - click
    - cloudpickle
    - colorama
    - commonmark
    - cryptography
    - cycler
    - dask
    - decorator
    - defusedxml
    - distributed
    - distro
    - docker
    - docker-compose
    - dockerpty
    - docopt
    - docutils
    - easydict
    - efficientnet-pytorch
    - entrypoints
    - fastparquet
    - filelock
    - flake
    - flake-bugbear
    - flask
    - fsspec
    - future
    - gast
    - gitdb
    - gitpython
    - google-api-core
    - google-api-python-client
    - google-auth
    - google-auth-httplib
    - google-auth-oauthlib
    - google-pasta
    - googleapis-common-protos
    - grpcio
    - gunicorn
    - hpy
    - heapdict
    - httplib
    - hyperopt
    - idna
    - imageio
    - imagesize
    - imgaug
    - importlib-metadata
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - iterative-stratification
    - itsdangerous
    - jedi
    - jeepney
    - jinja
    - jmespath
    - json
    - jsonpickle
    - jsonschema
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyterlab
    - jupyterlab-server
    - kaggle
    - keras-applications
    - keras-preprocessing
    - keyring
    - kiwisolver
    - lightgbm
    - llvmlite
    - locket
    - markdown
    - markupsafe
    - matplotlib
    - mccabe
    - mistune
    - more-itertools
    - msgpack
    - munch
    - nbconvert
    - nbformat
    - networkx
    - nltk
    - notebook
    - numba
    - numpy
    - oauthclient
    - oauthlib
    - opencv-python-headless
    - opt-einsum
    - packaging
    - pandas
    - pandocfilters
    - paramiko
    - parso
    - partd
    - pathspec
    - patsy
    - pexpect
    - pickleshare
    - pkginfo
    - plotly
    - pluggy
    - pretrainedmodels
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - py
    - py-cpuinfo
    - py-gfm
    - py-rouge
    - pyaml
    - pyarrow
    - pyasn
    - pyasn-modules
    - pycodestyle
    - pyflakes
    - pygments
    - pynacl
    - pyparsing
    - pyrsistent
    - pytest
    - python-dotenv
    - python-graphviz
    - python-slugify
    - pyvips
    - pywavelets
    - pyyaml
    - pyzmq
    - qtconsole
    - readme-renderer
    - recommonmark
    - regex
    - requests
    - requests-mock
    - requests-oauthlib
    - requests-toolbelt
    - retrying
    - rsa
    - stransfer
    - sacred
    - sacremoses
    - sandesh
    - scikit-image
    - scikit-learn
    - scikit-optimize
    - scipy
    - seaborn
    - secretstorage
    - sendtrash
    - sentencepiece
    - sh
    - smmap
    - smmap
    - snowballstemmer
    - sortedcontainers
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-rtd-theme
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - statsmodels
    - subword-nmt
    - tblib
    - tensorboard
    - tensorflow
    - tensorflow-estimator
    - termcolor
    - terminado
    - testpath
    - text-unidecode
    - texttable
    - thrift
    - tokenizers
    - toml
    - toolz
    - torch
    - torchvision
    - tornado
    - tqdm
    - traitlets
    - transformers
    - tsfresh
    - twine
    - typed-ast
    - typing-extensions
    - unidecode
    - uritemplate
    - urllib
    - wcwidth
    - webencodings
    - websocket-client
    - werkzeug
    - widgetsnbextension
    - wrapt
    - wtfml
    - xgboost
    - yawml
    - zict
    - zipp